

export const LOAD_EVENTS_REQUEST = 'LOAD_EVENTS_REQUEST';
export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
export const LOAD_EVENTS_FAILURE = 'LOAD_EVENTS_FAILURE';
export const AUTHENTICATION_API_REQUEST = 'AUTHENTICATION_API_REQUEST';
export const AUTHENTICATION_API_SUCCESS = 'AUTHENTICATION_API_SUCCESS';
export const AUTHENTICATION_API_FAILURE = 'AUTHENTICATION_API_FAILURE';

export const SAVE_AUTHENTICATION_STATE = 'SAVE_AUTHENTICATION_STATE';
